### ISSUE TITLE
Change peer dependency to point at latest `@xterm/xterm` ???

### ISSUE THREAD

**Issue by WebReflection** [strtok/xterm-readline#11]
This module seems to be abandoned but for our use case is working kinda great. However, we don't like legacy dependencies or even legacy peer dependencies so that every time CI install our stack it complains `xterm` is deprecated and so is some other part of this stack (something with `array.sort` now being stable).

Everything seems to work fine though with this plugin in latest XTerm and I wonder if there's any hope this package will update any time soon or if we should take over a fork and solve all the things ourselves, thank you.

**Comment by strtok** [comment]
Hello!

Do you have a PR you can submit with these dependency updates? Thanks!

**Comment by WebReflection** [comment]
@strtok I can provide such PR but I guess my question was: is this module abandoned? in such case I am going to fork it instead, because PRs even for dependencies smell like abandoned to me (or not maintained anymore). Thanks for any possible clarification around this topic.

**Comment by strtok** [comment]
It's not abandoned. I've just updated dependencies and published a new version. Let me know if there's any issues or please open a PR if you need any fixes. Thanks!

**Comment by WebReflection** [comment]
Apologies I've failed at remembering to close this issue before you had to ... I was testing and excited enough I forgot, it's all good and our warnings are gone. **Thank you!**
